unless Vagrant.has_plugin?("vagrant-vmware-esxi")
    system("vagrant plugin install vagrant-vmware-esxi")
end

Vagrant.configure("2") do |config|
    # Domain Controller
    config.vm.define "dc" do |dc|
        dc.vm.box = "gusztavvargadr/windows-server"
        dc.vm.provider "vmware_esxi" do |esxi|
            esxi.esxi_hostname = "10.10.10.5"
            esxi.esxi_username = "root"
            esxi.esxi_password = "1qaz2wsx!QAZ@WSX"
            esxi.esxi_disk_store = "datastore1"
            esxi.esxi_virtual_network = "VM Network"
            esxi.guest_numvcpus = "2"
            esxi.guest_memsize = "2048"
        end
        dc.vm.communicator = "winrm"
        dc.vm.hostname = "dc1"
    end
end