Vagrant.configure("2") do |config|
  config.vm.provision "powershell", inline: "[Environment]::SetEnvironmentVariable('VBOX_HOME', '$PWD/Virtual-Machines', 'User')"
  config.vm.provision "powershell", inline: "$env:VBOX_HOME"

  # Security Incident & Event Management (SIEM) Server
  config.vm.define "SIEM Server" do |siem|
    siem.vm.box = "deathlab/siem-server"
    siem.vm.provider "virtualbox" do |vb|
      vb.name = "SIEM Server"
      vb.gui = true
      vb.check_guest_additions = false
    end
  end
end

#   # Firewall
#   config.vm.define "firewall" do |firewall|
#     firewall.vm.box = "ksklareski/pfsense-ce"
#     firewall.vm.guest = :freebsd
#     firewall.vm.provider "virtualbox" do |vb|
#       vb.name = "Firewall"
#       vb.cpus = 2
#       vb.memory = 2048
#       vb.gui = false
#       vb.check_guest_additions = false
#     end
#     firewall.vm.network :private_network,
#       name: "VirtualBox Host-Only Ethernet Adapter",
#       ip: "192.168.5.254", 
#       netmask: "255.255.255.0"
#     firewall.vm.network "forwarded_port", guest: 80, host: 8888
#     firewall.vm.communicator = "ssh"
#     firewall.ssh.insert_key = $false # see Requirements
#     firewall.ssh.shell = "sh"
#     firewall.vm.hostname = "firewall"
#     firewall.vm.provision "file", source: "Configuration-Files/Firewall.xml", destination: "/tmp/config.xml"
#     firewall.vm.provision "shell", inline: "mv /tmp/config.xml /cf/conf/config.xml"
#     firewall.vm.provision "shell", inline: "rm /tmp/config.cache"
#   end

#   # Domain Controller
#   config.vm.define "dc" do |dc|
#     dc.vm.box = "salesforce/server2019"
#     dc.vm.provider "virtualbox" do |vb|
#       vb.name = "Domain-Controller"
#       vb.cpus = 2
#       vb.memory = 2048
#       vb.gui = false
#     end
#     dc.vm.network :private_network, 
#       name: "VirtualBox Host-Only Ethernet Adapter", 
#       ip: "192.168.5.10", 
#       netmask: "255.255.255.0"
#     dc.vm.communicator = "winrm"
#     dc.winrm.transport = "plaintext" # see Lab Requirements
#     dc.winrm.basic_auth_only = true # see Lab Requirements
#     dc.vm.hostname = "dc1"
#     dc.vm.provision "shell", path: "New-AdForest.ps1"
#     dc.vm.provision "shell", reboot: true # see Lab Requirements
#     dc.vm.provision "shell", path: "Set-DnsServer.ps1"
#     dc.vm.provision "shell", path: "Wait-ForAllRequiredServicesToStart.ps1"
#     dc.vm.provision "shell", path: "New-AdDomainAdmin.ps1"
#     dc.vm.provision "shell", path: "New-AdUserSet.ps1"
#     dc.vm.provision "shell", path: "New-GpoWallpaper.ps1"
#     dc.vm.provision "shell", path: "New-GpoDomainControllerTaskbar.ps1"
#     dc.vm.provision "shell", path: "New-GpoAuditPolicy.ps1"
#     dc.vm.provision "shell", path: "New-GpoWindowsRemoteManagement.ps1"
#     dc.vm.provision "shell", path: "New-GpoWindowsEventForwarding.ps1"
#   end

#   # Windows Event Collector (WEC) Server
#   config.vm.define "wec" do |wec|
#     wec.vm.box = "salesforce/server2019"
#     wec.vm.provider "virtualbox" do |vb|
#       vb.name = "WEC-Server"
#       vb.cpus = 2
#       vb.memory = 2048
#       vb.gui = false
#     end
#     wec.vm.network :private_network, 
#       name: "VirtualBox Host-Only Ethernet Adapter", 
#       ip: "192.168.5.11", 
#       netmask: "255.255.255.0"
#     wec.vm.communicator = "winrm"
#     wec.winrm.transport = "plaintext" # see Lab Requirements
#     wec.winrm.basic_auth_only = true # see Lab Requirements
#     wec.vm.hostname = "wec1"
#     wec.vm.provision "shell", path: "Set-DnsServer.ps1"
#     wec.vm.provision "shell", path: "Join-Domain.ps1"
#     wec.vm.provision "shell", reboot: true # see Lab Requirements
#   end

#   # App Server (Web Server, File Server)
#   config.vm.define "app" do |app|
#     app.vm.box = "salesforce/server2019"
#     app.vm.provider "virtualbox" do |vb|
#       vb.name = "App-Server"
#       vb.cpus = 2
#       vb.memory = 2048
#       vb.gui = false
#     end
#     app.vm.network :private_network, 
#       name: "VirtualBox Host-Only Ethernet Adapter", 
#       ip: "192.168.5.12", 
#       netmask: "255.255.255.0"
#     app.vm.communicator = "winrm"
#     app.winrm.transport = "plaintext" # see Lab Requirements
#     app.winrm.basic_auth_only = true # see Lab Requirements
#     app.vm.hostname = "app1"
#     app.vm.provision "shell", path: "Set-DnsServer.ps1"
#     app.vm.provision "shell", path: "Join-Domain.ps1"
#     app.vm.provision "shell", reboot: true # see Lab Requirements
#   end

#   # Security Incident & Event Management (SIEM) Server
#   config.vm.define "siem" do |siem|
#     siem.vm.box = "salesforce/server2019"
#     siem.vm.provider "virtualbox" do |vb|
#       vb.name = "SIEM-Server"
#       vb.cpus = 2
#       vb.memory = 2048
#       vb.gui = false
#     end
#     siem.vm.network :private_network,
#       name: "VirtualBox Host-Only Ethernet Adapter",
#       ip: "192.168.5.13", 
#       netmask: "255.255.255.0"
#     siem.vm.communicator = "ssh"
#     siem.vm.hostname = "siem"
#   end 

#   # Workstation
#   config.vm.define "ws" do |ws|
#     ws.vm.box = "StefanScherer/windows_10"
#     ws.vm.provider "virtualbox" do |vb|
#       vb.name = "Workstation"
#       vb.cpus = 2
#       vb.memory = 2048
#       vb.gui = false
#     end
#     ws.vm.network :private_network,
#       name: "VirtualBox Host-Only Ethernet Adapter",
#       ip: "192.168.5.69", 
#       netmask: "255.255.255.0"
#     ws.vm.communicator = "winrm"
#     ws.winrm.transport = "plaintext" # see Lab Requirements
#     ws.winrm.basic_auth_only = true # see Lab Requirements
#     ws.vm.hostname = "ws1"
#     ws.vm.provision "shell", path: "Provisioning-Scripts/Set-DnsServer.ps1"
#     ws.vm.provision "shell", path: "Provisioning-Scripts/Join-Domain.ps1"
#   end

#   # Adversary
#   config.vm.define "adversary" do |adversary|
#     adversary.vm.box = "kalilinux/rolling"
#     adversary.vm.provider "virtualbox" do |vb|
#       vb.name = "Adversary"
#       vb.cpus = 2
#       vb.memory = 4096
#       vb.gui = false
#     end
#     adversary.vm.network :private_network,
#       name: "VirtualBox Host-Only Ethernet Adapter",
#       ip: "192.168.5.86", 
#       netmask: "255.255.255.0"
#     adversary.vm.communicator = "ssh"
#     adversary.vm.hostname = "adversary"
#     adversary.vm.provision "shell", path: "Provisioning-Scripts/Adversary/Set-Wallpaper.sh"
#   end
# end