Vagrant.configure("2") do |config|
    unless Vagrant.has_plugin?("vagrant-vbguest") # see Requirements
      system("vagrant plugin install vagrant-vbguest") 
    end
  
    # Domain Controller
    config.vm.define "dc" do |dc|
      dc.vm.box = "salesforce/server2019"
      dc.vm.provider "virtualbox" do |vb|
        vb.name = "Domain-Controller"
        vb.cpus = 4
        vb.memory = 8192
        vb.gui = false
      end
      dc.vm.network :private_network, 
        name: "VirtualBox Host-Only Ethernet Adapter", 
        ip: "192.168.1.5", 
        netmask: "255.255.255.0"
      dc.vm.communicator = "winrm"
      dc.winrm.transport = "plaintext" # see Lab Requirements
      dc.winrm.basic_auth_only = true # see Lab Requirements
      dc.vm.hostname = "XOF5000DC1"
      dc.vm.provision "shell", path: "Provisioning-Scripts/Set-DnsServer.ps1"
      dc.vm.provision "shell", path: "Provisioning-Scripts/New-AdForest.ps1"
      dc.vm.provision "shell", reboot: true # see Lab Requirements
      dc.vm.provision "shell", path: "Provisioning-Scripts/Wait-ForAllRequiredServicesToStart.ps1"
      dc.vm.provision "shell", path: "Provisioning-Scripts/New-AdDomainAdmin.ps1"
    end
  
    # Workstation
    config.vm.define "ws" do |ws|
      ws.vm.box = "StefanScherer/windows_10"
      ws.vm.provider "virtualbox" do |vb|
        vb.name = "Workstation"
        vb.cpus = 4
        vb.memory = 8192
        vb.gui = false
      end
      ws.vm.network :private_network,
        name: "VirtualBox Host-Only Ethernet Adapter",
        ip: "192.168.1.69", 
        netmask: "255.255.255.0"
      ws.vm.communicator = "winrm"
      ws.winrm.transport = "plaintext" # see Lab Requirements
      ws.winrm.basic_auth_only = true # see Lab Requirements
      ws.vm.hostname = "XOF5000WS1"
      ws.vm.provision "shell", path: "Provisioning-Scripts/Set-DnsServer.ps1"
      ws.vm.provision "shell", path: "Provisioning-Scripts/Join-Domain.ps1"
      ws.vm.provision "shell", reboot: true # see Lab Requirements
    end
  end