Vagrant.configure("2") do |config|
    unless Vagrant.has_plugin?("vagrant-vmware-esxi")
        system("vagrant plugin install vagrant-vmware-esxi")
    end
    
    # Domain Controller
    config.vm.define "dc" do |dc|
        dc.vm.box = "StefanScherer/windows_2019"
        dc.vm.provider "vmware_esxi" do |esxi|
            esxi.esxi_hostname = "10.10.10.5"
            esxi.esxi_username = "root"
            esxi.esxi_password = "1qaz2wsx!QAZ@WSX"
            esxi.esxi_disk_store = "datastore1"
            esxi.esxi_virtual_network = "VM Network"
            esxi.guest_name = 'Domain-Controller'
            esxi.guest_numvcpus = "2"
            esxi.guest_memsize = "2048"
        end
        dc.vm.network :private_network, 
            name: "VirtualBox Host-Only Ethernet Adapter", 
            ip: "192.168.5.10", 
            netmask: "255.255.255.0"
        dc.vm.communicator = "winrm"
        dc.winrm.transport = "plaintext" # see Lab Requirements
        dc.winrm.basic_auth_only = true # see Lab Requirements
        dc.vm.hostname = "dc1"
        dc.vm.provision "shell", path: "Provisioning-Scripts/Domain-Controller/New-AdForest.ps1"
        dc.vm.provision "shell", reboot: true # see Lab Requirements
        dc.vm.provision "shell", path: "Provisioning-Scripts/Domain-Controller/Set-DnsServer.ps1"
        dc.vm.provision "shell", path: "Provisioning-Scripts/Domain-Controller/Wait-ForAllRequiredServicesToStart.ps1"
        dc.vm.provision "shell", path: "Provisioning-Scripts/Domain-Controller/New-AdDomainAdmin.ps1"
    end
end