Vagrant.configure("2") do |config|
  # install the Vagrant VMWare plugin if not installed
  unless Vagrant.has_plugin?("vagrant-vmware-desktop") 
    system("vagrant plugin install vagrant-vmware-desktop") 
  end

  # define which Vagrant box to use
  config.vm.box = "velociraptor"

  # set the Vagrant output name for this box
  config.vm.define "velociraptor"

  # configure provider-specific settings
  config.vm.provider "vmware_desktop" do |vmware|

    # set the virtual machine display name in VMWare
    vmware.vmx["displayname"] = "Velociraptor"

    # show the gui 
    vmware.gui = true
    vmware.cpus = 2
    vmware.memory = "2048"

    # mute the "allowlist" warning
    vmware.allowlist_verified = true
  end

  # set the SSH credentials
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  # provision the virtual machine
  config.vm.provision "shell", inline: <<-SHELL
    echo "hello" >> debug.log
  SHELL
  end