Vagrant.configure("2") do |config|
  unless Vagrant.has_plugin?("vagrant-vmware-desktop") 
    system("vagrant plugin install vagrant-vmware-desktop") 
  end
  config.vm.box = "velociraptor"
  config.vm.define "velociraptor"
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.vmx["displayname"] = "Velociraptor"
    vmware.gui = true
    vmware.cpus = 2
    vmware.memory = "2048"
    vmware.allowlist_verified = true
    vmware.vmx["ethernet0.connectionType"] = "Custom"
    vmware.vmx["ethernet0.vnet"] = "VMnet1" 
    vmware.vmx["ethernet1.connectionType"] = "Custom"
    vmware.vmx["ethernet1.vnet"] = "VMnet8" 
  end
  config.vm.network "private_network", type: "dhcp"
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.vm.provision "shell", inline: <<-SHELL
    echo "hello" >> debug.log
  SHELL
  end